export const DATA_EXPORT_TYPES = [
  "ingredients",
  "inventory",
  "recipes",
  "recipe_ingredients",
  "customers",
  "suppliers",
  "discounts",
] as const;

export type DataExportType = (typeof DATA_EXPORT_TYPES)[number];

export const DATA_TYPE_LABELS: Record<DataExportType, string> = {
  ingredients: "Ingredients",
  inventory: "Inventory stock",
  recipes: "Recipes (menu items)",
  recipe_ingredients: "Recipe BOM (ingredients per recipe)",
  customers: "Customers",
  suppliers: "Suppliers",
  discounts: "Discount codes",
};

export const TEMPLATE_HEADERS: Record<DataExportType, string[]> = {
  ingredients: [
    "name",
    "category",
    "default_unit",
    "sku",
    "barcode",
    "aliases",
    "notes",
    "is_active",
  ],
  inventory: [
    "name",
    "sku",
    "category",
    "ingredient_name",
    "quantity",
    "unit",
    "reorder_level",
    "cost_per_unit",
    "supplier_name",
    "storage_location",
    "is_active",
  ],
  recipes: [
    "name",
    "category",
    "description",
    "yield_quantity",
    "yield_unit",
    "sale_price",
    "barcode",
    "image_url",
    "instructions",
  ],
  recipe_ingredients: ["recipe_name", "ingredient_name", "quantity_required", "unit"],
  customers: ["name", "phone", "email", "notes"],
  suppliers: ["name", "contact_phone", "email", "address", "notes", "is_active"],
  discounts: [
    "code",
    "name",
    "type",
    "value",
    "min_order_amount",
    "is_active",
    "valid_from",
    "valid_to",
  ],
};

export const TEMPLATE_EXAMPLE_ROW: Record<DataExportType, string[]> = {
  ingredients: [
    "Mozzarella",
    "Dairy",
    "kg",
    "MOZZ-001",
    "8901234567890",
    "mozzarella cheese",
    "",
    "true",
  ],
  inventory: [
    "Mozzarella Block 1kg",
    "MOZZ-STK-001",
    "Dairy",
    "Mozzarella",
    "5",
    "kg",
    "2",
    "450",
    "Fresh Farms",
    "Cold room A",
    "true",
  ],
  recipes: [
    "Margherita Pizza",
    "Pizza",
    "Classic tomato and cheese",
    "1",
    "pcs",
    "299",
    "8901234567891",
    "",
    "Bake 12 min",
  ],
  recipe_ingredients: ["Margherita Pizza", "Mozzarella", "0.15", "kg"],
  customers: ["Rahul Sharma", "9876543210", "rahul@example.com", "Regular"],
  suppliers: ["Fresh Farms", "9123456780", "orders@freshfarms.com", "Pune", "", "true"],
  discounts: ["WELCOME10", "Welcome 10%", "PERCENT", "10", "200", "true", "", ""],
};
